### ISSUE TITLE
Add a couple options to squelch errors for certain CSS browser hacks

### ISSUE THREAD

**Issue by cvrebert** [w3c/css-validator#10]
Many sites these days unfortunately still need to accommodate IE9 (or, $DEITY forbid, IE8), and authors must frequently resort to CSS browser hacks to work around bugs/deficiencies in these browsers. However, they would still like to benefit from the CSS Validator's valuable error detection facilities when working on the CSS for their sites. I therefore propose the validator should add a couple options (disabled by default, and perhaps hidden in an "Advanced" pane) that would squelch errors about a couple of the simplest yet most common CSS hacks used to deal with these browsers. Specifically:
- An option to squelch errors about [IE<=9's proprietary `filter:` CSS property](https://msdn.microsoft.com/en-us/library/ms532853%28v=vs.85%29.aspx) (not to be confused with the same-named standard property from Filter Effects Module Level 1)
- An option to squelch errors about [the `\9` CSS property-value hack for IE6-8](http://browserhacks.com/#hack-ab1bcc7b3a6544c99260f7608f8e845e)

These currently lead to nasty "Value Error"s or "Parse Error"s, as opposed to more easily manageable "Property foo doesn't exist", "Feature foo doesn't exist for media bar", or "Sorry, the at-rule @-foo is not implemented." errors.

There is precedent for adding (small, limited) old-IE-specific accommodations to Web validators/specs; see for example https://github.com/validator/validator/pull/12 & https://www.w3.org/Bugs/Public/show_bug.cgi?id=27091

**Comment by cvrebert** [comment]
@ylafon Any thoughts on this?

**Comment by ylafon** [comment]
I'm always conflicted with this. On one hand, it's clearly invalid and must be highlighted, on the other hand it's needed for some UAs. We could add an option (false by default), like we have for vendor extensions (which is true by default).

**Comment by cvrebert** [comment]
Thirdly, it'd be nice to handle the `(min-width:0\0)` media query hack; see http://browserhacks.com/#hack-a60b03e301a67f76a5a22221c739dc64

**Comment by acerjp0514** [comment]
How come my Chromebook always paused/stalled when I debug a website for any reason just to see what's going on the script like if I press audit button on my developers option tool

**Comment by sideshowbarker** [comment]
> Thirdly, it'd be nice to handle the `(min-width:0\0)` media query hack; see http://browserhacks.com/#hack-a60b03e301a67f76a5a22221c739dc64

I‘ve raised PR #125 for that — because that seems to be at least as common in the wild as `\9` thing.

**Comment by sideshowbarker** [comment]
> An option to squelch errors about [IE<=9's proprietary `filter:` CSS property](https://msdn.microsoft.com/en-us/library/ms532853%28v=vs.85%29.aspx) (not to be confused with the same-named standard property from Filter Effects Module Level 1)

I think it would be best at this point to raise a separate new issue for that one (if you still think an option for special handling of it should be added) — since if/when the changes in #37 get merged (and  also #125), we could then close out this issue as resolved.

**Comment by sideshowbarker** [comment]
>> An option to squelch errors about [IE<=9's proprietary `filter:` CSS property](https://msdn.microsoft.com/en-us/library/ms532853%28v=vs.85%29.aspx) (not to be confused with the same-named standard property from Filter Effects Module Level 1)
>
> I think it would be best at this point to raise a separate new issue for that one (if you still think an option for special handling of it should be added) — since if/when the changes in #37 get merged (and  also #125), we could then close out this issue as resolved.

OK, I’ve now raised PR #134 for that. So if/when that and the others get merged, we could close this issue as completely resolved.

When I first read the mention of *“IE<=9's proprietary filter: CSS property”* in the description for this issue, I didn’t realize it was the same thing as the `progid:DXImageTransform.Microsoft` thing that’s used in the wild all over the place — e.g., in most of the Alexa top 50 sites.

For every single occurrence of that in a stylesheet, the checker currently (without the patch in PR #134 applied) generates at least *three* error messages:

*  *Value Error : background Missing a semicolon before the property name progid*
*  *Property progid doesn't exist : DXImageTransform*
*  *Parse Error DXImageTransform.Microsoft.gradient(startColorStr…*

…so as-is now, it creates a lot of extra noise in the checker results report.

So given how widely used that `progid:DXImageTransform.Microsoft` stuff is, it seems like there are a lot of sites/developers that could benefit from having the option provided in #134 to filter out those messages so that can be more clearly alerted to other errors they might not have otherwise noticed among the extra noise.

**Comment by cvrebert** [comment]
> So if/when that and the others get merged, we could close this issue as completely resolved.

Sounds good to me!

**Comment by sideshowbarker** [comment]
Closing this issue now, because fixes for the cases enumerated here have all been merged — in #37, #125, and #134. And #147 for the star hack also was merged.

So if there are other remaining hacks that are still widely-used enough to merit special handling in the checker, new issues should be opened for any of those

**Comment by cvrebert** [comment]
@ylafon Any estimate on when the next redeployment of https://jigsaw.w3.org/css-validator/ might be?

**Comment by ylafon** [comment]
@cvrebert I just push it now.
