### ISSUE TITLE
Validator warns that -webkit-backface-visibility is an unknown vendor extension, but it's fully documented

### ISSUE THREAD

**Issue by tmb-github** [w3c/css-validator#348]
```
.hidden-backface {
    -webkit-backface-visibility: hidden;
    backface-visibility: hidden;
}

```
The validator warns that -webkit-backface-visibility is an unknown vendor extension, but the whatwg compatibility table lists it, and both MDN and caniuse.com document that the only implementation of the style available on Safari/iOS is -webkit-backface-visibility.

See: https://compat.spec.whatwg.org/#css-simple-aliases
Also:  browser compatibility table: https://developer.mozilla.org/en-US/docs/Web/CSS/backface-visibility
And: https://caniuse.com/?search=backface-visibility

There's no other way to use backface-visibility on Safari/iOS.

```
-webkit-backface-visibility is an unknown vendor extension
```
![Untitled](https://user-images.githubusercontent.com/15718749/137612141-526bd885-84d5-4d62-84b2-8acec85502eb.jpg)

**Comment by tmb-github** [comment]
@cvrebert I closed the issue at the other validator Issue Tracker because it was mistakenly posted there instead of here. This validator issues the warning; the other does not.

**Comment by sideshowbarker** [comment]
The Compat spec is basically the one spec that doesn’t count as as spec for conformance requirements. That’s because basically everything in the Compat spec is meant to be considered deprecated and non-standard. And more specifically, the Compat spec only defines _implementation_ requirements for browsers — it does not defined _document-conformance_ requirements for authors.

The CSS checker and HTML checker check document-conformance requirements — not implementation-conformance requirements. And in general for authors, everything in the Compat spec should be considered “should not use”.

If the features in the Compat spec were appropriate for proper standardization, the features would be defined in the relevant WHATWG and W3C specs.

All that said, authors are free to use any features from the Compat spec that they want to — but one cost of that is, when they check their content with the CSS checker or HTML checker, they’re going to see warnings or errors about using those features.

Authors are also free to ignore or filter out those warnings or errors.
