### ISSUE TITLE
The provided error does not exist (any longer)

### ISSUE THREAD

**Issue by danieldegroot2** [w3c/css-validator#379]
https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fdonate.openstreetmap.org%2F

returns
> 388: `dotted\8` is not a `outline-color` value : `thin dotted\8`

Navigating to the css file https://donate.openstreetmap.org/base.css
yields no occurences of `outline-color`. The only occurence of `thin dotted\8` is with `outline`.

I think either the validator is using an outdated source, or reading the file incorrectly.

(Source file: https://github.com/osmfoundation/donation-drive/blob/master/base.css )

**Comment by sideshowbarker** [comment]
It seems like the solution is to remove the `\8` from wherever you have `dotted\8` in the stylesheet.

That error isn’t about the `outline-color` property but instead about the `outline-color` *value* for the `outline` property:

- https://developer.mozilla.org/en-US/docs/Web/CSS/outline#outline-color
- https://w3c.github.io/csswg-drafts/css-ui-4/#outline
- https://w3c.github.io/csswg-drafts/css-ui-4/#propdef-outline-color

So, apparently what’s happening is that because of the `\8`, the CSS checker doesn’t recognize that `dotted\8` as an outline style — which would instead just be `dotted` — and so it next tries to interpret it as a color. But there’s no color named `dotted\8`  either, so the checker stops right there and reports the error cited in the issue description.

For the error to be more clear about what the problem is, it might be better if it instead said:

> `dotted\8` is not a `outline-color` value, nor an `outline-style` value, nor an `outline-width` value

But even as it’s currently worded, it’s still pointing out exactly where the problem is — which is that `dotted\8` value.
