### ISSUE TITLE
Document how to compile/build this

### ISSUE THREAD

**Issue by cvrebert** [w3c/css-validator#6]

**Comment by cvrebert** [comment]
@ylafon Ping.

**Comment by cvrebert** [comment]
Ah, looks like this uses Apache Ant.
Perhaps I'll try Mavenizing this.

**Comment by sideshowbarker** [comment]
> Perhaps I'll try Mavenizing this.

Please don’t spend any time actually doing that until @ylafon weighs in on this. I’m not 100% certain how if feels about switching the build to maven but I would bet that he would prefer not to do that. I personally would also strongly prefer not to do that. I recognize what some of the advantages of maven are for certain kinds of projects, but I don’t think this is one of those kinds of projects (yet).

The advantages of continuing to use ant include:

1. **If it ain’t broke, don’t fix it.** There may be some issues or brokenness with the current build but if so don’t think they are serious, and if/when we identify any, it would be better to just fix them instead of completely replacing/rewriting the build.

2. **Ant has less dependencies and complexity.** I am no big fan of ant either. But relative to the alternatives for building Java, it has much fewer dependencies and less complexity. Sure that also makes it less powerful. But we don’t need anything powerful for this build. And sure, ant may be less elegant (or whatever), but it’s not a beauty contest. We already have something that as far as I can tell is working as expected (modulo whatever issues we might identify)—as ugly as it might be.

**Comment by cvrebert** [comment]
Yeah, step 1 is of course to fix the existing Ant build script; #15 does that.

I can't speak to number of dependencies. Maven would certainly be less tedious; a bunch of the JAR filenames are repeated in 5 places in the Ant build whereas they'd only be referenced once in a `pom.xml`. There is also mindshare to consider. This is admittedly anecdotal, but my impression is that Ant isn't too popular these days compared to Maven for Java projects, so it's a little extra barrier to entry (e.g. I had to install Ant on my box just for this); YMMV of course. I agree that Maven can definitely get complex if you're doing complex things, but as you say, css-validator's build is extremely vanilla.
