### ISSUE TITLE
utf-8 chars not supported?

### ISSUE THREAD

**Issue by crazyx13th** [w3c/css-validator#82]
hey there,

thanks for this service! I have a small problem:

with 
`@charset "utf-8";`
```
.⛺e{
   font-family:Raleway,sans-serif;
   color:#d9b75b;
}
```

I got inside "direct-input":
![grafik](https://user-images.githubusercontent.com/8912561/33076434-033792b2-cecd-11e7-8f97-d966956cf73a.png)

but same inside uri check
![grafik](https://user-images.githubusercontent.com/8912561/33076551-50ecf4ca-cecd-11e7-8a61-808ba807a5a8.png)

![grafik](https://user-images.githubusercontent.com/8912561/33076752-edab1288-cecd-11e7-8922-74740d9d6fe4.png)

please help, thx!

greetings
crazyx13th

**Comment by dd8** [comment]
I came across the same problem testing some CSS 2.1 test suite URLs with the CSS Validator. The following (which test CSS unicode support works in browsers) show up as errors in Jigsaw:

http://test.csswg.org/suites/css2.1/20110323/html4/ident-004.htm 
Parse Error .怀ident, .one { color: green; }
http://test.csswg.org/suites/css2.1/20110323/html4/ident-005.htm
Lexical error at line 4, column 8. Encountered: "\u6000" (24576), after : "" .iden怀t怀, .one { color: green; }

The root cause is likely this production in CssParser.jj

  | < #NONASCII   : ["\200"-"\377"] >

This is from the CSS 2.1 recommendation, but only works if the CSS tokenizer uses 8-bit UTF-8 internally. I'm guessing that JavaCC uses the 16-bit UTF-16 Java 'char' type (UTF-16) internally and the range should be "\u0080"-"\uFFFF" **

https://www.w3.org/Style/css2-updates/REC-CSS2-20110607-errata.html#s.4.1.1b

** also need to consider Unicode characters outside the Basic Multilingual Plane in the range U+10000 to U+10FFFF, but in Java UTF-16 these are represented as a pair of char values, the first from the high-surrogates range, (\uD800-\uDBFF), the second from the low-surrogates range (\uDC00-\uDFFF) so probably covered by "\u0080"-"\uFFFF"

**Comment by sideshowbarker** [comment]
@crazyx13th Thanks much for taking time to report this. I’ve raised PR #114 with a fix.

@dd8 Thanks for the suggested change — I used it as-is for PR #114.

> The root cause is likely this production in CssParser.jj
> 
> ```
> | < #NONASCII : ["\200"-"\377"] >
> ```
> … the range for JavaCC should be "\u0080"-"\uFFFF"

Yup

> also need to consider Unicode characters outside the Basic Multilingual Plane in the range U+10000 to U+10FFFF, but in Java UTF-16 these are represented as a pair of char values,… so probably covered by "\u0080"-"\uFFFF"

Yes that’s the case as far as I can tell. I tested with some code points greater than U+FFFF and they’re handled as expected; for example, the following:

```css
.🎪e{
   font-family:Raleway,sans-serif;
   color:#d9b75b;
}
```
…which takes @crazyx13th’s test case from the issue description and replaces the ⛺ (U+26FA 'TENT') with 🎪 (U+1F3AA 'CIRCUS TENT'). And the CSS checker handles it as expected.
```
